server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nbaez001/in28minutes-spring-boot-2.git
          searchPaths: config-service-repo
          default-label: master
          force-pull: true
          username: nbaez001
          password: ${NBAEZ001_GITHUB_TOKEN}