version: '3.8'

services:
  mysql:
    image: mysql:8-oracle
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: social-media-db
      MYSQL_USER: social-media-user
      MYSQL_PASSWORD: 1234
    command: --character-set-server=utf8 --collation-server=utf8_spanish_ci
    volumes:
      - mysql_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysql_volume: